### ISSUE TITLE
Assess the OrgBook UX Project output and decide on an approach

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-angular#21]
Please take the content provided by Claire from the OrgBook UX project and document what changes are needed and the best approach to use in making the changes.

- What is just "pure" web development work and what effort would you say there is to do that starting from the OrgBook BC UI repo?  What would the difference be in having a random (but presumably good) Web Developer doing the work vs. you with your existing knowledge of the code base?  My hope is that we can give it to someone else, as we have lots to keep you busy, but we do need to know if it would be significantly easier for you.  BTW - as part of that, what refactoring/revamping/throwing away from the existing code base would you suggest doing?  What is the current tech stack? Should we keep it?
- The next part is harder.  What API changes/additions are needed for this new design?  Go through the screens, the existing APIs and see what is missing. API additions/adjustments is work that I expect will be assigned to you.
- The next part is (I think) harder still.  What new concepts are in this UI that don't fit the "credential agnostic, topic-oriented" nature of Aries VCR that will be needed to support the new UI design?  Are there things that require too much hard-coding of data in Aries VCR for this?  What data does the issuer have to tell Aries VCR (and Aries VCR have to track) to enable the UI?
- The previous item leads to a related task -- after you identify the sharp edges/impossible things to do, and then you, Ian and myself having a discussion to see what can be done, should be done and shouldn't be done.

Thanks

**Comment by swcurran** [comment]
@amanji , @ianco -- please add links to the input materials, outputs from the effort and add any other notes to this ticket.

Thanks!

**Comment by ianco** [comment]
The recommendation from the DTS techies is to do a clean start using vue.js

This is based on the amount of effort required to refactor/clean up the existing code, plus to rewrite the UI, which would be about the same as just starting from scratch using vue.

The two most complex functions in OrgBook (search/advanced search plus the org view/timeline) both need extensive rewrites, so adding in the refactor of the data service, reorg of code, etc, etc, this increases the effort of updating the existing code.

With a fresh start using vue, there is no technical debt that needs to be cleaned up.

It’s a simpler framework, so would be easier to onboard new developers

(We briefly discussed other frameworks such as react, but since we already have a few demo’s using vue, and there aren't any other frameworks that have a lot of support in the team, so we felt it best to recommend vue.)

Akiff is putting together an estimate but probably around a month of a full time resource to do most of the work

(If we put together detailed specs around how the search, timeline and filtering are supposed to work, then prob a month plus some testing.
If we start with some more general specs and do the work more iteratively, this would add a couple of weeks to iterate through this functionality.)

**Comment by amanji** [comment]
Basis of the discussion surrounding work effort: [OrgBook Re-design Work Assessment.pdf](https://github.com/bcgov/orgbook-bc-client/files/6517590/OrgBook.Re-design.Work.Assessment.pdf)

**Comment by amanji** [comment]
Upon reviewing [`orgbook-api`](https://github.com/bcgov/orgbook-api) where a demo reconstituted search functionality (with facets) and a basic Topic details page (with various panels and credential verification), the total implementation took approximately 18-20 working days (with a cursory understanding of the API). Given how concrete the current wireframes are, I am inclined to suggest that the first pass of a complete rewrite could possibly be accomplished within 1-1.5 month(s) (along with some additional time to for testing and iterative improvements if needed. I concur that perhaps Vue.js is used as this is consistent with the newer projects that are using Vue.js, and could possibly allow components to be shared across these projects (although I'm impartial to the framework and in fact prefer as close to vanilla JS implementations as possible).

**Comment by amanji** [comment]
I would also like to suggest that we structure the codebase into feature modules, i.e Search, Topic/Entity, About, Contact, etc
